# Generated by Django 4.2.26 on 2025-11-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_identifier', models.CharField(max_length=255)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('browser', models.CharField(default='Unknown', max_length=100)),
                ('operating_system', models.CharField(default='Unknown', max_length=100)),
                ('referrer', models.CharField(default='Direct', max_length=500)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr_generator.qrcode')),
            ],
            options={
                'verbose_name_plural': 'Scan Analytics',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['qr_code', '-scanned_at'], name='qr_generato_qr_code_a76dbe_idx'), models.Index(fields=['user_identifier'], name='qr_generato_user_id_fa3480_idx')],
            },
        ),
    ]
