# Generated by Django 4.2.26 on 2025-12-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_generator', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_type',
            field=models.CharField(choices=[('url', 'URL'), ('file', 'File'), ('dynamic', 'Dynamic')], max_length=10),
        ),
    ]
