# Generated by Django 4.2.27 on 2025-12-04 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "qr_generator",
            "0005_qrcode_is_active_qrcode_name_qrcode_short_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="qr_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
        migrations.CreateModel(
            name="QRUTMParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("utm_source", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("utm_term", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "utm_content",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "qr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utm",
                        to="qr_generator.qrcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRCustomization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "qr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customization",
                        to="qr_generator.qrcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRAdvancedOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password_protection",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("use_short_url", models.BooleanField(default=False)),
                (
                    "qr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advanced",
                        to="qr_generator.qrcode",
                    ),
                ),
            ],
        ),
    ]
