# Generated by Django 4.2.27 on 2025-12-05 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qr_generator", "0006_alter_qrcode_qr_image_qrutmparameters_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRDeviceRedirects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_url", models.URLField(blank=True, null=True)),
                ("desktop_url", models.URLField(blank=True, null=True)),
                ("default_url", models.URLField(blank=True, null=True)),
                (
                    "qr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_redirects",
                        to="qr_generator.qrcode",
                    ),
                ),
            ],
        ),
    ]
